version: '1.0'
stages:
  - prepare
  - test
  - package
  - build
steps:
  main_clone:
    type: git-clone
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
    stage: prepare
  env_init:
    stage: prepare
    image: alpine:latest
    commands:
      - export MAVEN_OPTS="-Dmaven.repo.local=/codefresh/volume/m2"
      - cf_export MAVEN_OPTS
  mvn_test:
    stage: test
    image: maven:3.5.2-jdk-8-alpine
    commands:
      - mvn clean test
  mvn_package:
    stage: package
    image: maven:3.5.2-jdk-8-alpine
    commands:
      - mvn clean package
  docker_build:
    type: build
    stage: build
    image_name: example-app
    working_directory: ./
    tag: 'latest'
    dockerfile: Dockerfile